mex -output a -largeArrayDims ...
  -I"C:\Program Files\Microsoft SDKs\Windows\v7.1\Include" ...
  -LPsychSourceGL\Cohorts\PortAudio ...
  -IPsychSourceGL\Source\Common\PsychPortAudio ...
  -Iportaudio\src\common ...
  -IReo\Reo ...
  -LReo\x64\Release ...
  a.c ...
  kernel32.lib user32.lib winmm.lib delayimp.lib Reo.lib...
  -lportaudio_x64 LINKFLAGS="$LINKFLAGS /DELAYLOAD:portaudio_x64.dll"