
mex -largeArrayDims ...
  -I"C:\Program Files\Microsoft SDKs\Windows\v7.1\Include" ...
  -Iportaudio\include ...
  -Iportaudio\src\common ...
  -IReo\Reo ...
  -LReo\x64\Release ...
  open.c reoml.c ...
  delayimp.lib reo.lib ...
  -lportaudio_x64 LINKFLAGS="$LINKFLAGS /DELAYLOAD:portaudio_x64.dll"

mex -largeArrayDims ...
  -I"C:\Program Files\Microsoft SDKs\Windows\v7.1\Include" ...
  -Iportaudio\include ...
  -Iportaudio\src\common ...
  -IReo\Reo ...
  -LReo\x64\Release ...
  close.c reoml.c ...
  delayimp.lib reo.lib ...
  -lportaudio_x64 LINKFLAGS="$LINKFLAGS /DELAYLOAD:portaudio_x64.dll"

mex -largeArrayDims ...
  -I"C:\Program Files\Microsoft SDKs\Windows\v7.1\Include" ...
  -Iportaudio\include ...
  -Iportaudio\src\common ...
  -IReo\Reo ...
  -LReo\x64\Release ...
  start.c ...
  delayimp.lib reo.lib ...
  -lportaudio_x64 LINKFLAGS="$LINKFLAGS /DELAYLOAD:portaudio_x64.dll"

mex -largeArrayDims ...
  -I"C:\Program Files\Microsoft SDKs\Windows\v7.1\Include" ...
  -Iportaudio\include ...
  -Iportaudio\src\common ...
  -IReo\Reo ...
  -LReo\x64\Release ...
  stop.c ...
  delayimp.lib reo.lib ...
  -lportaudio_x64 LINKFLAGS="$LINKFLAGS /DELAYLOAD:portaudio_x64.dll"

mex -largeArrayDims ...
  -I"C:\Program Files\Microsoft SDKs\Windows\v7.1\Include" ...
  -Iportaudio\include ...
  -Iportaudio\src\common ...
  -IReo\Reo ...
  -LReo\x64\Release ...
  post.c reoml.c...
  delayimp.lib reo.lib ...
  -lportaudio_x64 LINKFLAGS="$LINKFLAGS /DELAYLOAD:portaudio_x64.dll"

mex -largeArrayDims ...
  -I"C:\Program Files\Microsoft SDKs\Windows\v7.1\Include" ...
  -Iportaudio\include ...
  -Iportaudio\src\common ...
  -IReo\Reo ...
  -LReo\x64\Release ...
  info.c ...
  delayimp.lib reo.lib ...
  -lportaudio_x64 LINKFLAGS="$LINKFLAGS /DELAYLOAD:portaudio_x64.dll"

% mex -outdir +aud -output pas -largeArrayDims ...
%   -I"C:\Program Files\Microsoft SDKs\Windows\v7.1\Include" ...
%   -LPsychSourceGL\Cohorts\PortAudio ...
%   -IPsychSourceGL\Source\Common\PsychPortAudio ...
%   -Iportaudio\src\common ...
%   -IReo\Reo ...
%   -LReo\x64\Release ...
%   pa_stream.c...
%   kernel32.lib user32.lib winmm.lib delayimp.lib ...
%   -lportaudio_x64 LINKFLAGS="$LINKFLAGS /DELAYLOAD:portaudio_x64.dll"